/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package travelagency;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class FORMDOMESTICTRAVELS extends javax.swing.JFrame {
    public FORMDOMESTICTRAVELS() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jLabel3.setText("jLabel3");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Please chose the radio \nbutton which correspond \nto the available travel\ndestinations in India.\n");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Domestic Travels");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe Script", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 102));
        jLabel1.setText("DOMESTIC  TRAVELS");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 440, 50));

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("1");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, 40, -1));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("2");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, -1, -1));

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("3");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, -1, -1));

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("4");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        jPanel4.add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, 40, -1));

        buttonGroup1.add(jRadioButton5);
        jRadioButton5.setText("5");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });
        jPanel4.add(jRadioButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 550, -1, -1));

        buttonGroup1.add(jRadioButton6);
        jRadioButton6.setText("6");
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });
        jPanel4.add(jRadioButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 600, -1, -1));

        buttonGroup1.add(jRadioButton7);
        jRadioButton7.setText("7");
        jRadioButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton7ActionPerformed(evt);
            }
        });
        jPanel4.add(jRadioButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 40, -1));

        buttonGroup1.add(jRadioButton8);
        jRadioButton8.setText("8");
        jRadioButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton8ActionPerformed(evt);
            }
        });
        jPanel4.add(jRadioButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/travelagency/proceedarmod.png"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 610, 110, 70));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/travelagency/indmapmod.png"))); // NOI18N
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 680));

        jPanel7.setBackground(new java.awt.Color(204, 204, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "About Your Destination", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 14), new java.awt.Color(153, 0, 153))); // NOI18N
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jTextArea2.setWrapStyleWord(true);
        jScrollPane2.setViewportView(jTextArea2);

        jPanel7.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 410, 430));

        jPanel4.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 110, 430, 490));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 0, 204));
        jLabel6.setText("Hi");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, 80, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, 140, 20));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 0, 153));
        jLabel8.setText("Enter Mobile No");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 60, 120, 20));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });
        jPanel4.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 60, 220, -1));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1040, 680));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/travelagency/backmodmodmod.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 60));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/travelagency/homemod.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 0, 70, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 760));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
jTextArea2.setText("Maharashtra \n"+"\n"
      
        + "Is a state in the western region of India \n"
        
        + "and is India's second-most populous state\n"
        + "and third-largest state by area.\n"
        + "Spread over 307,713 km2 (118,809 sq mi),\n"
        + "it is bordered by the Arabian Sea to the west \n"
        
        + "and the Indian states of Karnataka, Telangana, Goa etc.\n"
        + "It is also the world's second-most populous subnational entity. \n"
        
        + "It has over 112 million inhabitants and its capital,\n"
        
        + "Mumbai, has a population of approximately 18 million.\n"
        
        + "Nagpur is Maharashtra's second capital as well as its winter capital."); 


    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
   jTextArea2.setText("Andhra Pradesh \n" +"\n"
        
           + "Is one of the 29 states of India. \n"
           + "The state, which is situated on the southeastern coast of the country\n"
           
           + "is the eighth-largest state in India covering an area of 162,970 km2 .\n"
           + "This state is tenth-largest by population with 49,386,799 inhabitants.\n"
           + "The largest city in the state is Visakhapatnam.\n"
           + "Andhra Pradesh hosted 121.8 million visitors in 2015\n"
           
           + " making it the third most-visited Indian state. \n"
           
           + "The Tirumala Venkateswara Temple is one of the world's most visited religious sites\n"
           
           + "with 18.25 million visitors per year.\n"
           
           + "Other pilgrimage centers in Andhra Pradesh include the Srikalahasteeswara Temple\n"
           + "the Mallikarjuna Jyotirlinga at Srisailam,");     
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
jTextArea2.setText("Rajasthan\n"+"\n"
        + "Is India's largest state by area \n"
        + "It is located on the north western side of the India,\n"
        
        + "where it comprises most of the wide and inhospitable Thar Desert\n"
        + "and shares a border with the Pakistani provinces of Punjab  and Sindh\n"
        
        + "Elsewhere it is bordered by five other Indian states: Punjab ; Haryana and Uttar Pradesh ; Madhya Pradesh; and Gujarat ."
        + "\n" +
"Major features include the ruins of the Indus Valley Civilisation at Kalibanga;\n"
        
        + " A Jain pilgrimage site at Rajasthan's only hill station, Mount Abu, in the ancient Aravalli mountain range;\n"
        + " and, in eastern Rajasthan, the Keoladeo National Park near Bharatpur, a World Heritage Site known for its bird life. \n"
        
        + "Rajasthan is also home to three national tiger reserves, the Ranthambore National Park in Sawai Madhopur,\n"
        + " Sariska Tiger Reserve in Alwar and Mukundra Hill Tiger Reserve in Kota.");        
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
jTextArea2.setText("Assam  is a state in Northeast India, situated south of the "
        + "eastern Himalayas along the Brahmaputra and Barak River valleys. Assam "
        
        + "covers an area of 78,438 km2 (30,285 sq mi)."
        + " The state is bordered by Bhutan and the state of Arunachal Pradesh"
        + " to the north; Nagaland and Manipur to the east;"
        + " Meghalaya, Tripura, Mizoram and Bangladesh to the south;"
        
        + " and West Bengal to the west via the Siliguri Corridor,"
        + " a 22 kilometres (14 mi) strip of land that connects the state to the rest of India.\n" +
        
"\n" +
"Assam is known for Assam tea and Assam silk. "
        + "The state has conserved the one-horned Indian rhinoceros from near extinction"
        + ", along with the wild water buffalo, "
        
        + "pygmy hog, tiger and various species of Asiatic birds, "
        + "and provides one of the last wild habitats for the Asian elephant."
        
        + " The Assamese economy is aided by wildlife tourism to Kaziranga National Park "
        
        + "and Manas National Park, "
        + "which are World Heritage Sites. Sal tree forests are found in the state which, "
        
        + "as a result of abundant rainfall, look green all year"
        + " round. Assam receives more rainfall than most parts of India");        
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
jTextArea2.setText("Tamil Nadu is one of the 29 states of India."
        + " Its capital and largest city is Chennai (formerly known as Madras). "
        
        + "Tamil Nadu lies in the southernmost part of the Indian Peninsula and is bordered by the union territory "
        + "of Puducherry and the South Indian states of Kerala, Karnataka, and Andhra Pradesh."
        + " It is bounded by the Eastern Ghats on the north, by the Nilgiri, the Anamalai Hills, and Kerala on the west,"
        
        + " by the Bay of Bengal in the east, by the Gulf of Mannar and the Palk Strait on the southeast, "
        
        + "and by the Indian Ocean on the south. The state shares a maritime border with the nation of Sri Lanka.\n" +
"\n" +
"Tamil Nadu is the eleventh-largest state in India by area and the sixth-most populous. "
        + "The state was ranked third among states in India according to the Human Development Index in 2015, "
        
        + "and is the second-largest state economy in India with ₹15.96 lakh crore (US$240 billion) in gross domestic product "
        
        + "after Maharashtra. Tamil Nadu was ranked as one of the top seven developed states in India based on a"
        
        + " 2013 report published by the Reserve Bank of India. Its official language is Tamil, which is one of the longest-surviving "
        + "classical languages in the world.");       
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
jTextArea2.setText("Kerala, is a state in South India on the Malabar Coast. "
        + "It was formed on 1 November 1956 following the States Reorganisation Act by combining Malayalam-speaking regions. "
        + "Spread over 38,863 km2 (15,005 sq mi), it is bordered by Karnataka to the north and northeast,"
        
        + "Tamil Nadu to the east and south, and the Lakshadweep Sea to the west. With 33,387,677 inhabitants as per the 2011 Census,"
        + " Kerala is the thirteenth-largest Indian state by population. "
        
        + "It is divided into 14 districts with the capital being Thiruvananthapuram."
        
        + " Thiruvananthapuram is the largest city in the state. Malayalam is the most widely spoken language "
        
        + "and is also the official language of the state.\n" +
"\n" +
"The Chera Dynasty was the first prominent kingdom based in Kerala."
        + " The Ay kingdom in the deep south and the Ezhimala kingdom in the north formed the other kingdoms "
        
        + "in the early years of the Common Era (CE or AD). The region had been a prominent spice exporter since 3000 BCE."
        
        + " The region's prominence in trade was noted in the works of Pliny as well as the Periplus around 100 CE. In the 15th century"
        + " the spice trade attracted Portuguese traders to Kerala, and paved the way for European colonisation of India."
        
        + " At the time of Indian independence movement in the early 20th century, there were two major princely states"
        + " in Kerala-Travancore State and the Kingdom of Cochin. They united to form the state of Thiru-Kochi in 1949."
        
        + " The Malabar region, in the northern part of Kerala had been a part of the Madras province of British India,"
        
        + " which later became a part of the Madras State post-independence. ");        
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    private void jRadioButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton7ActionPerformed
jTextArea2.setText("Delhi , officially the National Capital Territory of Delhi (NCT),"
        + "is a city and a union territory of India. It is bordered by Haryana"
        
        + "on three sides and by Uttar Pradesh to the east. The NCT covers an area of 1,484 square kilometres"
        
        + "(573 sq mi). According to the 2011 census, Delhi city proper's population was over 11 million"+
"The area around Delhi was probably inhabited before the second millennium BC and there"
        
        + "is evidence of continuous inhabitation since at least the 6th century BC."+"\n"
        + "The city is believed to be the site of Indraprastha, the legendary capital of the Pandavas "
        
        + "in the Indian epic Mahabharata.] According to Mahabharata, this land was initially a huge mass"
        
        + " of forests called 'Khandavaprastha' which was burnt down to build the city of Indraprastha."
        + "The earliest architectural relics date back to the Maurya period (c. 300 BC); in 1966,"
        
        + "an inscription of the Mauryan Emperor Ashoka (273–235 BC) was discovered near Srinivaspuri.");         
    }//GEN-LAST:event_jRadioButton7ActionPerformed

    private void jRadioButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton8ActionPerformed
jTextArea2.setText("Jammu and Kashmir  is a state in northern India, "
        + "often denoted by the acronym J&K. It is located mostly in the Himalayan mountains,"
        
        + " and shares borders with the states of Himachal Pradesh and Punjab to the south. "
        
        + "The Line of Control separates it from the Pakistani-administered territories of Azad Kashmir"
        + " and Gilgit-Baltistan in the west and north respectively, and a Line of Actual Control "
        
        + "separates it from the Chinese-administered territory of Aksai Chin in the east. " + "\n" +
"Jammu and Kashmir is home to several valleys such as the Kashmir Valley,"
        
        + " Tawi Valley, Chenab Valley, Poonch Valley, Sind Valley and Lidder Valley. "
        
        + "The main Kashmir Valley is 100 km (62 mi) wide and 15,520.3 km2 (5,992.4 sq mi) in area. "
        
        + "The Himalayas divide the Kashmir valley from Ladakh while the Pir Panjal range, which encloses the valley "
        
        + "from the west and the south, separates it from the Great Plains of northern India. Along the northeastern flank o"
        
        + "f the Valley runs the main range of the Himalayas. This densely settled and beautiful valley has an average height"
        
        + " of 1,850 metres (6,070 ft) above sea-level but the surrounding Pir Panjal range has an average elevation of 5,000 metres");        
    }//GEN-LAST:event_jRadioButton8ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String a="";
String name=jLabel7.getText();
String mobile=jTextField1.getText();
if(jRadioButton1.isSelected())
a="Maharashtra";
else if(jRadioButton2.isSelected())
a="Andhra Pradesh";
else if(jRadioButton3.isSelected())
a="Rajasthan";
else if(jRadioButton4.isSelected())
a="Assam";
else if(jRadioButton5.isSelected())
a="Tamil Nadu";
else if(jRadioButton6.isSelected())
a="Kerala";
else if(jRadioButton7.isSelected())
a="Delhi";
else
a="Jammu";
if(!mobile.isEmpty()&&!name.isEmpty())
{
   try {
            Class.forName("java.sql.DriverManager");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/itravel", "root", "rootpw");
            Statement stmt = (Statement) con.createStatement();
            String query = "INSERT INTO state VALUES(  '"+a+"','"+mobile+"','"+name+"');";
            stmt.executeUpdate(query);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        } 
}
else
{
    JOptionPane.showMessageDialog(this,"Please Enter your Mobile Number");
}
   
   
   if(jRadioButton1.isSelected()) 
        { 
    new MAHARASHTRA().setVisible(true);
    this.dispose();
        }
else
     if(jRadioButton2.isSelected())
     {
new ANDHRAPRADESH().setVisible(true);
 this.dispose();
}

else
     if(jRadioButton3.isSelected())
     {
new RAJASTHAN().setVisible(true);
 this.dispose();
}

else 
   if(jRadioButton4.isSelected())
   {
    new ASSAM().setVisible(true);
   this.dispose();  
}

else 
     if(jRadioButton5.isSelected())
     {
    new TAMILNADU().setVisible(true);
    this.dispose(); 
}

else
     if(jRadioButton6.isSelected())
     {
    new KERALA().setVisible(true);
     this.dispose();
}

else
     if(jRadioButton7.isSelected())
     {
    new DELHI().setVisible(true);
     this.dispose();
}

else
    if(jRadioButton8.isSelected())
    {
    new JAMMU().setVisible(true); 
     this.dispose();
}
else
JOptionPane.showMessageDialog(this, " PLEASE SELECT A CITY ", "CITY NOT SELECTED", JOptionPane.WARNING_MESSAGE);
        


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
new DestinationMode4().setVisible(true);
this.dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
    new Introduction().setVisible(true);
     this.dispose();    
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
 
    }//GEN-LAST:event_jButton1MouseClicked

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
 char ch = evt.getKeyChar();

        if (!(Character.isDigit(ch))) {
            evt.consume();
        }   
       
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
 String mobile=jTextField1.getText();
        try {
            Class.forName("java.sql.DriverManager");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/itravel", "root", "rootpw");
            Statement stmt = (Statement) con.createStatement();
            String query = "Select Name From form6 Where MobileNo='"+mobile+"' ;";
         ResultSet rs=   stmt.executeQuery(query);
         if(rs.next())
             {
             String Name=rs.getString("Name");
           
             jLabel7.setText(Name);
             }
              }
         
         
         catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }        
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FORMDOMESTICTRAVELS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FORMDOMESTICTRAVELS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FORMDOMESTICTRAVELS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FORMDOMESTICTRAVELS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FORMDOMESTICTRAVELS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
