/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package travelagency;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.awt.Toolkit;
import java.sql.DriverManager;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class TRAVELFLIGHTBOOKING extends javax.swing.JFrame {

    /**
     * Creates new form TRAVELFLIGHTBOOKING
     */
    public TRAVELFLIGHTBOOKING() {
    initComponents();
        setIcon();
        String cost =jTextField2.getText();
        jButton1.setEnabled(false);
         jDateChooser1.setMinSelectableDate(new Date());
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jLabel21 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Flight Booking");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BOOK YOUR FLIGHT");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 340, 30));
        jPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 160, 140, 30));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ROUND TRIP", "ONE WAY", " " }));
        jComboBox1.setSelectedIndex(2);
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 160, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("FROM");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 130, -1));

        jComboBox2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ECONOMY", "PREMIUM ECONOMY", "BUSINESS", " " }));
        jComboBox2.setSelectedIndex(3);
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 150, -1));

        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 240, 140, 40));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "RAJIV GANDHI  INTERNATIONAL AIRPORT", "CHHATRAPATI SHIVAJI INTERNATIONAL AIRPORT", "COIMBATORE AIRPORT", "TRIVANDRUM INTERNATIONAL AIRPORT", "LOKPROIYA INTERNATIONAL AIRPORT(Assam)", "INDIRA GANDHI INTERNATIONAL AIRPORT", "CHENNAI INTERNATIONAL AIRPORT", " " }));
        jComboBox3.setSelectedIndex(7);
        jPanel1.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 270, 30));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "RAJIV GANDHI  INTERNATIONAL AIRPORT", "CHHATRAPATI SHIVAJI INTERNATIONAL AIRPORT", "COIMBATORE AIRPORT", "TRIVANDRUM INTERNATIONAL AIRPORT", " LOKPROIYA INTERNATIONAL AIRPORT(Assam)", "INDIRA GANDHI INTERNATIONAL AIRPORT", "CHENNAI INTERNATIONAL AIRPORT", " " }));
        jComboBox4.setSelectedIndex(7);
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, 270, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 204));
        jLabel4.setText("(CURRENTLY ONLY 7 AIRPORTS ARE AVAILABLE THROUGHOUT INDIA)");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 530, 20));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("TO");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("TRAVEL DATE");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 140, 160, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("TRAVEL TYPE");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 130, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("NO. OF");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 80, -1));

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 40, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 270, 20));

        jLabel18.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, 260, 20));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("FLIGHT CLASS");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 160, -1));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 710, -1, -1));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 620, -1, -1));

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 760, -1, -1));

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 590, -1, -1));

        buttonGroup1.add(jRadioButton5);
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 460, -1, -1));

        buttonGroup1.add(jRadioButton6);
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, -1, -1));

        buttonGroup1.add(jRadioButton7);
        jRadioButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 740, -1, -1));

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("NAME");
        jLabel21.setToolTipText("Primary Passenger");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 70, 80, 30));
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 100, 190, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 51, 0));
        jLabel7.setText("FROM AIRPORT:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/travelagency/indmodmodmap.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 500, 550));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/travelagency/backmodmodmod.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 60));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 204));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/travelagency/FLIGHTFARE.PNG"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 950, 230));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/travelagency/proceedarmod.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 750, 120, 60));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 360, 450, 320));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, 330, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 0, 204));
        jLabel6.setText("Destination sites:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, 350, 20));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/travelagency/homemod.png"))); // NOI18N
        jLabel10.setText("jLabel10");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 0, 70, 60));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(153, 0, 153));
        jLabel19.setText("GET TOTAL COST  (per person) >>>");
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 700, 270, 30));

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 730, 250, -1));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/travelagency/submitmod.png"))); // NOI18N
        jLabel20.setText("jLabel20");
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 770, 110, 30));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/travelagency/removemod.png"))); // NOI18N
        jLabel22.setText("jLabel22");
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 770, 90, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 960, 810));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
if("".equals(jTextField1.getText()))
        JOptionPane.showMessageDialog(this,"Enter No. of Passengers");


   else if(jComboBox3.getSelectedIndex()==7 || jComboBox4.getSelectedIndex()==7)
       {
    JOptionPane.showMessageDialog(this, " Please Fill in the Primary  & Destination Airport", "Invalid Data", JOptionPane.WARNING_MESSAGE);   
       }
else
    if(     jComboBox3.getSelectedIndex()==0 )
{
        new TICKETPAGAIR().setVisible(true); 
        this.dispose(); 
}
else 
    if (jComboBox3.getSelectedIndex()==1) 
{
   new TICKETPAGAIR2().setVisible(true); 
       this.dispose();   
}
else
        if (jComboBox3.getSelectedIndex()==2) 
{
   new TICKETPAGAIR3().setVisible(true); 
       this.dispose();   
}
else
        if (jComboBox3.getSelectedIndex()==3) 
{
   new TICKETPAGAIR4().setVisible(true); 
       this.dispose();  
}

else
        if (jComboBox3.getSelectedIndex()==4) 
{
   new TICKETPAGAIR5().setVisible(true); 
     this.dispose();    
}

else
        if (jComboBox3.getSelectedIndex()==5) 
{
   new TICKETPAGAIR6().setVisible(true); 
       this.dispose(); 
}
else
       if(jComboBox3.getSelectedIndex()==6)
{
    new TICKETPAGAIR7().setVisible(true);
  this.dispose(); 
}
      
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
 jTextArea1.setText("Kerala Destinations : Backwaters");
        jLabel5.setIcon(new ImageIcon(TravelAgency.class.getResource("bkwtrmod.png")));     
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton7ActionPerformed
   jTextArea1.setText("Tamil Nadu Destinations : Brihadeeshwara Temple");
        jLabel5.setIcon(new ImageIcon(TravelAgency.class.getResource("tntemplemod.png")));       
    }//GEN-LAST:event_jRadioButton7ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
 jTextArea1.setText("Guwathi Destinations");
        jLabel5.setIcon(new ImageIcon(TravelAgency.class.getResource("wtrflguwti.jpg")));        
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
  jTextArea1.setText("Delhi Destinations: India Gate,Qutub Minar ,Agra Fort etc.");;
        jLabel5.setIcon(new ImageIcon(TravelAgency.class.getResource("dliarptmod.png")));       
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
 jTextArea1.setText("Mumbai Destinations: Gateway of India ");
        jLabel5.setIcon(new ImageIcon(TravelAgency.class.getResource("gtmod.png")));             
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
  jTextArea1.setText("Andhra Pradesh Destinations : Charminar");
        jLabel5.setIcon(new ImageIcon(TravelAgency.class.getResource("chrmnrmod.png")));          
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String a =jTextField2.getText();
String b =jTextField3.getText();
String c =jTextField1.getText();
        if(jComboBox3.getSelectedIndex()== 7)
{
   jLabel17.setText("Enter From Airport");
}
        if(jComboBox4.getSelectedIndex()== 7)
        {
    jLabel18.setText("Enter Destination Airport");
        }
        
      if(jComboBox3.getSelectedIndex()!=7)  
      {
          jLabel17.setText("");
      }
        
       if(jComboBox4.getSelectedIndex()!=7)  
      {
          jLabel18.setText("");
      }  
     
        if(jComboBox2.getSelectedIndex()== 3)
        {
    JOptionPane.showMessageDialog(this, " Please Fill in the Class of Your Flight", "Invalid Data", JOptionPane.WARNING_MESSAGE);
        }
        
        if(jComboBox1.getSelectedIndex()== 2)
        {
    JOptionPane.showMessageDialog(this, " Please Fill in the Trip Type", "Invalid Data", JOptionPane.WARNING_MESSAGE);
        }
        
        else if(jComboBox1.getSelectedIndex()!=2 
                &&jComboBox2.getSelectedIndex()!=3 
                &&jComboBox3.getSelectedIndex()!=7 
                && jComboBox4.getSelectedIndex()!=7 )
            
        {
            new Passengerdetails().setVisible(true);
       this.dispose(); 
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
new commonformtoflightandrlwy().setVisible(true);
this.dispose(); 
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
 new Introduction().setVisible(true);
        this.dispose();      
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
 char ch =evt.getKeyChar();

if(!(Character.isDigit(ch)))
{
    evt.consume();
} 

// TODO add your handling code here:
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
if(jComboBox3.getSelectedIndex()==0
        &&jComboBox1.getSelectedIndex()==0
        &&jComboBox2.getSelectedIndex()==0
        &&jComboBox4.getSelectedIndex()!=7) 
{
    jTextField2.setText("Rs.23,000");
}

else 
    if(jComboBox3.getSelectedIndex()==1
        &&jComboBox1.getSelectedIndex()==1
        &&jComboBox2.getSelectedIndex()==1
            &&jComboBox4.getSelectedIndex()!=7) 
{
    jTextField2.setText("Rs.19700");
}
else 
        if(jComboBox3.getSelectedIndex()==2
        &&jComboBox1.getSelectedIndex()==1
        &&jComboBox2.getSelectedIndex()==2) 
{
    jTextField2.setText("Rs.16,300");
}

else 
        if(jComboBox3.getSelectedIndex()==3
        &&jComboBox1.getSelectedIndex()==0
        &&jComboBox2.getSelectedIndex()==1
        &&jComboBox4.getSelectedIndex()!=7) 
{
    jTextField2.setText("Rs.14,900");
}


else 
        if(jComboBox3.getSelectedIndex()==4
        &&jComboBox1.getSelectedIndex()==1
        &&jComboBox2.getSelectedIndex()==2
        &&jComboBox4.getSelectedIndex()!=7        ) 
{
    jTextField2.setText("Rs.21,789");
}

else
         if(jComboBox3.getSelectedIndex()==5
        &&jComboBox1.getSelectedIndex()==0
        &&jComboBox2.getSelectedIndex()==1
        &&jComboBox4.getSelectedIndex()!=7        ) 
{
    jTextField2.setText("Rs.23,971");
}

else
         if(jComboBox3.getSelectedIndex()==6
        &&jComboBox1.getSelectedIndex()==1
        &&jComboBox2.getSelectedIndex()==0
        &&jComboBox4.getSelectedIndex()!=7        ) 
{
    jTextField2.setText("Rs.30,485");
}

else 
         if(jComboBox3.getSelectedIndex()==0
        &&jComboBox1.getSelectedIndex()==1
        &&jComboBox2.getSelectedIndex()==2
        &&jComboBox4.getSelectedIndex()!=7         ) 
{
    jTextField2.setText("Rs.15,456");
}

else
          if(jComboBox3.getSelectedIndex()==1
        &&jComboBox1.getSelectedIndex()==0
        &&jComboBox2.getSelectedIndex()==2
        &&jComboBox4.getSelectedIndex()!=7          ) 
{
    jTextField2.setText("Rs.16,789");
}

else
          if(jComboBox3.getSelectedIndex()==2
        &&jComboBox1.getSelectedIndex()==0
        &&jComboBox2.getSelectedIndex()==1
        &&jComboBox4.getSelectedIndex()!=7          ) 
{
    jTextField2.setText("Rs.15,456");
}

else
          if(jComboBox3.getSelectedIndex()==3
        &&jComboBox1.getSelectedIndex()==1
        &&jComboBox2.getSelectedIndex()==0
        &&jComboBox4.getSelectedIndex()!=7          )
{
    jTextField2.setText("Rs.12,874");
}

else
           if(jComboBox3.getSelectedIndex()==4
        &&jComboBox1.getSelectedIndex()==0
        &&jComboBox2.getSelectedIndex()==1
        &&jComboBox4.getSelectedIndex()!=7           ) 
{
    jTextField2.setText("Rs.21,784");
}

else
            if(jComboBox3.getSelectedIndex()==5
        &&jComboBox1.getSelectedIndex()==1
        &&jComboBox2.getSelectedIndex()==2
        &&jComboBox4.getSelectedIndex()!=7            ) 
{
    jTextField2.setText("Rs.32,746");
}
else 
            if(jComboBox3.getSelectedIndex()==6
        &&jComboBox1.getSelectedIndex()==0
        &&jComboBox2.getSelectedIndex()==2
        &&jComboBox4.getSelectedIndex()!=7            ) 
{
    jTextField2.setText("Rs.33,440");
}

else 
            if(jComboBox3.getSelectedIndex()==1
        &&jComboBox1.getSelectedIndex()==2
        &&jComboBox2.getSelectedIndex()==0
        &&jComboBox4.getSelectedIndex()!=7            ) 
{
    jTextField2.setText("Rs.11,452");
}

else 
            if(jComboBox3.getSelectedIndex()==2
        &&jComboBox1.getSelectedIndex()==1
        &&jComboBox2.getSelectedIndex()==0
        &&jComboBox4.getSelectedIndex()!=7            ) 
{
    jTextField2.setText("Rs.18,991");
}

else 
            if(jComboBox3.getSelectedIndex()==3
        &&jComboBox1.getSelectedIndex()==1
        &&jComboBox2.getSelectedIndex()==2
        &&jComboBox4.getSelectedIndex()!=7            ) 
{
    jTextField2.setText("Rs.28,441");
}

else 
            if(jComboBox3.getSelectedIndex()==4
        &&jComboBox1.getSelectedIndex()==1
        &&jComboBox2.getSelectedIndex()==0
         &&jComboBox4.getSelectedIndex()!=7           ) 
{
    jTextField2.setText("Rs.27,458");
}

else 
            if(jComboBox3.getSelectedIndex()==5
        &&jComboBox1.getSelectedIndex()==1
        &&jComboBox2.getSelectedIndex()==0
        &&jComboBox4.getSelectedIndex()!=7            ) 
{
    jTextField2.setText("Rs.16,448");
}

else
            if(jComboBox3.getSelectedIndex()==6
        &&jComboBox1.getSelectedIndex()==1
        &&jComboBox2.getSelectedIndex()==2
        &&jComboBox4.getSelectedIndex()!=7            ) 
{
    jTextField2.setText("Rs.35,785");
}

else 
            if(jComboBox3.getSelectedIndex()==2
        &&jComboBox1.getSelectedIndex()==1
        &&jComboBox2.getSelectedIndex()==1
        &&jComboBox4.getSelectedIndex()!=7            ) 
{
    jTextField2.setText("Rs.41,785");
}
else 
            if(jComboBox3.getSelectedIndex()==3
        &&jComboBox1.getSelectedIndex()==0
        &&jComboBox2.getSelectedIndex()==0
        &&jComboBox4.getSelectedIndex()!=7            ) 
{
    jTextField2.setText("Rs.17,000");
}
else 
            if(jComboBox3.getSelectedIndex()==5
        &&jComboBox1.getSelectedIndex()==1
        &&jComboBox2.getSelectedIndex()==1
        &&jComboBox4.getSelectedIndex()!=7            ) 
{
    jTextField2.setText("Rs.16,000");
}
else
            if(jComboBox3.getSelectedIndex()==0
        &&jComboBox1.getSelectedIndex()==0
        &&jComboBox2.getSelectedIndex()==1
         &&jComboBox4.getSelectedIndex()!=7           ) 
{
    jTextField2.setText("Rs.15000");
}
else
            if(jComboBox3.getSelectedIndex()==2
        &&jComboBox1.getSelectedIndex()==0
        &&jComboBox2.getSelectedIndex()==0
                    ) 
{
    jTextField2.setText("Rs.14,980");
}
else
            if(jComboBox3.getSelectedIndex()==6
        &&jComboBox1.getSelectedIndex()==0
        &&jComboBox2.getSelectedIndex()==1
         &&jComboBox4.getSelectedIndex()!=7           ) 
{
    jTextField2.setText("Rs.19,992");
}
else 
            if(jComboBox3.getSelectedIndex()==4
        &&jComboBox1.getSelectedIndex()==0
        &&jComboBox2.getSelectedIndex()==2
         &&jComboBox4.getSelectedIndex()!=7           ) 
{
    jTextField2.setText("Rs.17,450");
}
else 
            if(jComboBox3.getSelectedIndex()==6
        &&jComboBox1.getSelectedIndex()==1
        &&jComboBox2.getSelectedIndex()==1
        &&jComboBox4.getSelectedIndex()!=7            ) 
{
    jTextField2.setText("Rs.12,999");
    
}
else
            if(jComboBox3.getSelectedIndex()==6
        &&jComboBox1.getSelectedIndex()==0
        &&jComboBox2.getSelectedIndex()==0
        &&jComboBox4.getSelectedIndex()!=7            ) 
{
    jTextField2.setText("Rs.28,446");
}
else 
            if(jComboBox3.getSelectedIndex()==5
        &&jComboBox1.getSelectedIndex()==0
        &&jComboBox2.getSelectedIndex()==2
         &&jComboBox4.getSelectedIndex()!=7           ) 
{
    jTextField2.setText("Rs.29,990");
}
else 
            if(jComboBox3.getSelectedIndex()==5
        &&jComboBox1.getSelectedIndex()==0
        &&jComboBox2.getSelectedIndex()==0
        &&jComboBox4.getSelectedIndex()!=7            ) 
{
    jTextField2.setText("Rs.17,452");
}
else 
            if(jComboBox3.getSelectedIndex()==4
        &&jComboBox1.getSelectedIndex()==0
        &&jComboBox2.getSelectedIndex()==0
        &&jComboBox4.getSelectedIndex()!=7            ) 
{
    jTextField2.setText("Rs.18,456");
}
else 
            if(jComboBox3.getSelectedIndex()==4
        &&jComboBox1.getSelectedIndex()==1
        &&jComboBox2.getSelectedIndex()==1
         &&jComboBox4.getSelectedIndex()!=7           ) 
{
    jTextField2.setText("Rs.14,559");
}
else 
            if(jComboBox3.getSelectedIndex()==3
        &&jComboBox1.getSelectedIndex()==1
        &&jComboBox2.getSelectedIndex()==1
        &&jComboBox4.getSelectedIndex()!=7            ) 
{
    jTextField2.setText("Rs.23,447");
}
else 
            if(jComboBox3.getSelectedIndex()==2
        &&jComboBox1.getSelectedIndex()==0
        &&jComboBox2.getSelectedIndex()==2
        &&jComboBox4.getSelectedIndex()!=7            ) 
{
    jTextField2.setText("Rs.17,447");
}
else 
            if(jComboBox3.getSelectedIndex()==1
        &&jComboBox1.getSelectedIndex()==0
        &&jComboBox2.getSelectedIndex()==0
        &&jComboBox4.getSelectedIndex()!=7            ) 
{
    jTextField2.setText("Rs.16,554");
}
else
            if(jComboBox3.getSelectedIndex()==1
        &&jComboBox1.getSelectedIndex()==0
        &&jComboBox2.getSelectedIndex()==1
        &&jComboBox4.getSelectedIndex()!=7            ) 
{
    jTextField2.setText("Rs.25,445");
}
else 
            if(jComboBox3.getSelectedIndex()==1
        &&jComboBox1.getSelectedIndex()==1
        &&jComboBox2.getSelectedIndex()==2
        &&jComboBox4.getSelectedIndex()!=7            ) 
{
    jTextField2.setText("Rs.19,991");
}
else
            if(jComboBox3.getSelectedIndex()==0
        &&jComboBox1.getSelectedIndex()==0
        &&jComboBox2.getSelectedIndex()==2
         &&jComboBox4.getSelectedIndex()!=7           ) 
{
    jTextField2.setText("Rs.29,000");
}
else 
            if(jComboBox3.getSelectedIndex()==0
        &&jComboBox1.getSelectedIndex()==1
        &&jComboBox2.getSelectedIndex()==0
         &&jComboBox4.getSelectedIndex()!=7           ) 
{
    jTextField2.setText("Rs.11,000");
}
else
            if(jComboBox3.getSelectedIndex()==0
        &&jComboBox1.getSelectedIndex()==1
        &&jComboBox2.getSelectedIndex()==1
                    ) 
{
    jTextField2.setText("Rs.17,482");
}
else 
            if(jComboBox3.getSelectedIndex()==1
        &&jComboBox1.getSelectedIndex()==1
        &&jComboBox2.getSelectedIndex()==0
        &&jComboBox4.getSelectedIndex()!=7            ) 
{
    jTextField2.setText("Rs.34,441");
}
else 
            if(jComboBox3.getSelectedIndex()==7
        &&jComboBox1.getSelectedIndex()==2
        &&jComboBox2.getSelectedIndex()==3
         &&jComboBox4.getSelectedIndex()!=7           ) 
{
  jTextField2.setText("Select The Appropriate Combo Boxes");
}
else 
            if(jComboBox3.getSelectedIndex()==3
        &&jComboBox1.getSelectedIndex()==0
        &&jComboBox2.getSelectedIndex()==2
         &&jComboBox4.getSelectedIndex()!=7           ) 
{
  jTextField2.setText("Rs.21,998");
}


else
{
jTextField2.setText("Invalid Input Re-select Again");
}// TODO add your handling code here:
    }//GEN-LAST:event_jLabel19MouseClicked

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
 jTextArea1.setText("Mahabalipuram: Shore Temple ");
        jLabel5.setIcon(new ImageIcon(TravelAgency.class.getResource("madrasmod.png")));

    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked

        
        String cost=jTextField2.getText();   
        String Name =jTextField3.getText();
        String people =jTextField1.getText();
        Date date = jDateChooser1.getDate();
        if( cost.isEmpty()||Name.isEmpty()||people.isEmpty()||date.equals(null)||jComboBox1.getSelectedIndex()==2 
                ||jComboBox2.getSelectedIndex()==3 
                ||jComboBox3.getSelectedIndex()==7 
                || jComboBox4.getSelectedIndex()==7) {
           JOptionPane.showMessageDialog(this,"Please enter the details or Select 'Get Total Cost'");
        }
        else {
                try {
                Class.forName("java.sql.DriverManager");
                Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/itravel", "root", "rootpw");
                Statement stmt = (Statement) con.createStatement();
                String query = "INSERT INTO cost VALUES(  '" +cost+ "','" + Name + "','" + people + "','"+date+"');";
                stmt.executeUpdate(query);
                } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
                
                }  
                jButton1.setEnabled(true);// TODO add your handling code here:
        }                // TODO add your handling code here:
    }//GEN-LAST:event_jLabel20MouseClicked

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
String Name=jTextField3.getText();
       if(Name.isEmpty())
       {
          JOptionPane.showMessageDialog(this,"Please enter the Name"); 
       }
       else
       {
        try {
            Class.forName("java.sql.DriverManager");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/itravel", "root", "rootpw");
            Statement stmt = (Statement) con.createStatement();
            String query = "Delete  From cost Where NameOfPrimaryPassenger='"+Name+"';";
            stmt.executeUpdate(query);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        } 
       }        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel22MouseClicked

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
Double m=Double.parseDouble(jTextField1.getText());
if(m>10)
{
    JOptionPane.showMessageDialog(this,"Enter no of passengers lesser than 10");
    jTextField1.setText("");
}
    }//GEN-LAST:event_jTextField1KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TRAVELFLIGHTBOOKING.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TRAVELFLIGHTBOOKING.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TRAVELFLIGHTBOOKING.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TRAVELFLIGHTBOOKING.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TRAVELFLIGHTBOOKING().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables

     private void setIcon() {

     setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("fltmod.png")));
    }
}
